accounting/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'accounting'

urlpatterns = [
    # path('', views.AccountingDashboardView, name="accounting_dashboard"), 
    path('transactions/', views.TransactionsListView.as_view(), name="transactions_list"),
    path('transactions/subject/<str:subject>/', views.TransactionsListView.as_view(), name="transactions_list_subject"),
    path('transactions/subject/<str:subject>/account/<str:bank>/', views.TransactionsListView.as_view(), name="transactions_list_subject_bank"),

    path('add-payment/', views.AddPayment.as_view(), name="add_payment"),
    path('add-receive/', views.AddRecieve.as_view(), name="add_receive"),
    path('remove-transaction/<int:pk>/', views.RemoveTransactionView, name="remove_transaction"),
    path('bank-accounts/', views.BankAccountListView.as_view(), name="bank_accounts_list"),
    path('transaction-subjects/', views.TransactionSubjectsListView.as_view(), name="transaction_subjects_list"),
    path('add-transation-subject/', views.AddTransactionSubject.as_view(), name="add_transaction_subject"),
    path('add-transation-subject/<int:pk>/', views.UpdateTransactionSubject.as_view(), name="update_transaction_subject"),
]

ai/urls.py
from django.urls import path
from . import views

app_name = 'ai'

urlpatterns = [
    path('models-list/add/', views.AiModelAddView, name='add_model'),
    path('models-list/', views.AiModelsListView, name='ai_models_list'),
    path('test/', views.AiView, name='ai'),
        
    path('chats-list/', views.ChatListView, name='ai_chats_list'),
    path('reports/', views.ChatReportView, name='ai_chats_report'),
    path('image/new/', views.AiImageView, name='ai_image_new_chat'),
    
    path('image/<str:chat_id>/', views.AiImageView, name='ai_image_continue_chat'),  # For continuing existing chat
    
    path('edit-prompt/<int:message_id>/', views.EditPromptView, name='ai_edit_prompt'),
    path('<str:chat_id>/', views.AiCreateNewChatView, name='ai_continue_chat'),
    path('', views.AiCreateNewChatView, name='ai_create'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('bookstore/', include('bookstore.urls', namespace='bookstore')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('quizes/', include('quizes.urls', namespace='quizes')),
    path('accounting/', include('accounting.urls', namespace='accounting')),
    path('api/', include('api.urls', namespace='api')),
    path('videos/', include('videos.urls', namespace='videos')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('ai/', include('ai.urls', namespace='ai')),
    path('restaurants/', include('restaurants.urls', namespace='restaurants')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('accounts/', include('accounts.urls',)),
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('generals.urls')),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounting/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
import uuid 
from django.conf import settings

from quizes.models import TimeStampedModel


class TransactionActiveManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(active=True)
    

class BankAccount(TimeStampedModel):
    title = models.CharField(
        _('Account title'),
        max_length=150,
        unique=True,        
    )
    bank_name = models.CharField(
        max_length=50,
        null=True, 
        blank=True,
    )
    card_number = models.CharField(
        _('Card number'),
        max_length=16,
        null=True, 
        blank=True        
    )
    account_number = models.CharField(
        _('Account number'),
        max_length=20,
        null=True, 
        blank=True
    )
    BIN = models.CharField(
        'BIN',
        max_length=24,
        null=True, 
        blank=True
    )
    interest_rate = models.DecimalField(
        max_digits=4,
        decimal_places=2,
        default=0
    )   
    initial_level = models.DecimalField(
        max_digits=settings.DEFAULT_MAX_DIGIT,
        decimal_places=0, 
        default=0
    )
    current_level = models.DecimalField(
        max_digits=settings.DEFAULT_MAX_DIGIT,
        decimal_places=0, 
        default=0
    )

    class Meta:
        verbose_name = _('Bank account')
        verbose_name_plural = _('Bank accounts')
        ordering = ('-title', )
    
    def __str__(self):
        return self.title
    
    def get_transactions_sum(self):
        return sum(t.amount_rec - t.amount_pay for t in self.transactions.all())
    
    # def save(self, *args, **kwargs):        
    #     self.current_level = self.initial_level - self.get_transactions_sum() 
    #     return super().save(*args, **kwargs) 

class TransactionSubject(TimeStampedModel):
    title = models.CharField(
        max_length=100,
        unique=True,                
    )
    # https://docs.djangoproject.com/en/4.1/ref/models/fields/#enumeration-types
    class TransactionKind(models.TextChoices):
        PAYMENT = 'pay', _('Payment')
        RECEIVE = 'rec', _('Receive')
    transaction_kind = models.CharField(
        max_length=3,
        choices=TransactionKind.choices,
        default=TransactionKind.PAYMENT,
    )
    @property
    def get_subject_sum_pay(self):
        return sum(t.amount_pay for t in self.transaction_set.filter(active=True))
    @property
    def get_subject_sum_rec(self):
        return sum(t.amount_rec for t in self.transaction_set.filter(active=True))

    class Meta:
        verbose_name = _('Transaction subject')
        verbose_name_plural = _('Transaction subjects')
        ordering = ('-pk', )

    def __str__(self):
        return self.title

class Transaction(TimeStampedModel):
    uuid = models.UUIDField(		
		default = uuid.uuid4,
		editable = False
    )
    amount_pay = models.DecimalField(
        _('Pay amount'),
        max_digits=settings.DEFAULT_MAX_DIGIT,
        decimal_places=0, 
        default=0
    )
    amount_rec = models.DecimalField(
        _('Receive amount'),
        max_digits=settings.DEFAULT_MAX_DIGIT,
        decimal_places=0, 
        default=0
    )
    # show the bank account at the time of transaction
    account_level = models.DecimalField(
        _('Account level'),
        max_digits=settings.DEFAULT_MAX_DIGIT,
        decimal_places=0, 
        default=0
    )
    date = models.DateTimeField(
        _('Transaction date'),
        null=True,
        blank=True
    )
    bank_account = models.ForeignKey(
        BankAccount,
        on_delete=models.SET_NULL,
        null=True, 
        blank=True,
        related_name='transactions'
    )
    registrar = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True, 
        blank=True
    )    
    subject = models.ForeignKey(
        TransactionSubject,
        on_delete=models.SET_NULL,                
        null=True, 
        blank=True
    )
    description = models.TextField(
        _('Description'),
        null=True, 
        blank=True
    )
    receipt_image = models.ImageField(
        _('Receipt image'),
        upload_to='accounting/receipt',
        null=True, 
        blank=True
    )
    receipt_file = models.FileField(
        _('Receipt file'),
        upload_to='accounting/receipt',
        null=True, 
        blank=True
    )
    active = models.BooleanField(
        default=True
    )

    # managers
    objects = models.Manager()
    active_trans = TransactionActiveManager()

    class Meta:
        verbose_name = _('Transaction')
        verbose_name_plural = _('Transactions')
        ordering = ('-pk', )

    def __str__(self):
        desc = self.description if self.description else ''
        if self.amount_pay:
            return f"{str(self.amount_pay)} {desc}" 
        elif self.amount_rec:
            return f"{str(self.amount_rec)} {desc}"         
    
    def update_account_level(self):
        return self.account_level + self.bank_account.initial_level

    def save(self, *args, **kwargs):
        if not self.date:
            self.date = self.created
        # this one should be calculated in the view not in the model
        # self.account_level = self.bank_account.current_level - self.amount_pay + self.amount_rec
        return super().save(*args, **kwargs)    

accounting/forms.py
from django import forms

from .models import Transaction, BankAccount, TransactionSubject


class PayForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)        
        self.fields['subject'].queryset = TransactionSubject.objects.filter(transaction_kind='pay')
        self.fields['description'].required = True
        self.fields['bank_account'].required = True
    class Meta:
        model = Transaction
        fields = [
            'amount_pay', 'description', 'subject', 'bank_account', # 'date', 'receipt_image', 'receipt_file'
        ]
        widgets = {
            'amount_pay': forms.TextInput(attrs={'autofocus': 'autofocus'}),
        }

class RecForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)        
        self.fields['subject'].queryset = TransactionSubject.objects.filter(transaction_kind='rec')
        self.fields['description'].required = True
        self.fields['bank_account'].required = True
    class Meta:
        model = Transaction
        fields = [
            'amount_rec', 'description', 'subject', 'bank_account', #'date', 'receipt_image', 'receipt_file'
        ]
        widgets = {
            'amount_rec': forms.TextInput(attrs={'autofocus': 'autofocus'}),
        }



PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 5)]

class DateForm(forms.Form):
    day = forms.TypedChoiceField(
        choices=[(i, str(i)) for i in range(1, 32)],
        coerce=int,
        label=''
    )
    month = forms.TypedChoiceField(
        choices=[(i, str(i)) for i in range(1, 13)],
        coerce=int,
        label=''
    )
    year = forms.TypedChoiceField(
        choices=[(i, str(i)) for i in range(2023, 2024)],
        coerce=int,
        label=''
    )
    

templates/accounting/_accounting_header.html
{% load i18n crispy_forms_tags %}
<div class="row">
  <div class="col-md-4">
    <a href="{% url 'accounting:add_payment' %}" class="btn btn-sm {% if accSection == 'pay' %}btn-warning{% else %}btn-outline-warning{% endif %} my-2">{% trans "Payment" %}</a>        
    <a href="{% url 'accounting:add_receive' %}" class="btn btn-sm ms-2 {% if accSection == 'rec' %}btn-warning{% else %}btn-outline-warning{% endif %} my-2">{% trans "Recieve" %}</a>
    <a href="{% url 'accounting:transactions_list' %}" class="btn btn-sm ms-2 {% if accSection == 'transaction' %}btn-warning{% else %}btn-outline-warning{% endif %} my-2">{% trans "Transactions" %}</a>
    <a href="{% url 'accounting:bank_accounts_list' %}" class="btn btn-sm  {% if accSection == 'bank' %}btn-warning{% else %}btn-outline-warning{% endif %} my-2">{% trans "Accounts" %}</a>
    <a href="{% url 'accounting:transaction_subjects_list' %}" class="btn btn-sm  {% if accSection == 'subject' %}btn-warning{% else %}btn-outline-warning{% endif %} my-2">{% trans "Subjects" %}</a>
    {% if accSection == 'transaction' %}    
  </div>
  <div class="col-md-6">
      <span class="text-light">{% trans "From" %}: </span>       
      {{ from_date }}
      <span class="text-light">{% trans "To" %}: </span>       
      {{ to_date }}
      <input type="submit" value="{% trans 'Submit' %}" class="btn btn-warning btn-sm ms-3">
    </form>
  </div>
  <div class="col-md-2">    
    <form class="" action="." method="get">
      <span class="input-group ">
        <input type="text" class="form-control" placeholder="" name="search" aria-label="Search" aria-describedby="button-addon1">
        <button class="btn btn-outline-secondary" type="submit"  id="button-addon1">{% trans "Search" %}</button>
      </span>
    </form>
  </div>  
  
  {% endif %}
</div>
  

templates/accounting/_transactions_list.html
{% load i18n humanize %}
<div class="table-responsive">
<table class="table table-striped table-dark">
    <thead>
        <tr>
            <th>#</th>
            <th>{% trans "Date/Time" %}</th>
            <th>{% trans "Description" %}</th>
            <th>{% trans "Subject" %}</th>
            <th>
                {% trans "Payment" %}
                <br>
                <span class="bg-light text-danger px-2 rounded">{{ pay_sum | intcomma:False }}</span>
            </th>
            <th>
                {% trans "Recieve" %}
                <br>
                <span class="bg-light text-success px-2 rounded">{{ rec_sum | intcomma:False }}</span>
            </th>
            <th>{% trans "Account level" %}</th>
            <th>{% trans "Babnk account" %}</th>
            <th>{% trans "Remove" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for t in object_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                {% if t.date %}
                {{ t.date }}
                {% else %}
                {{ t.created }}
                {% endif %}</td>
            <td>{{ t.description }}</td>
            <td>
                {% if from_date_date %}
                <a href="{% url 'accounting:transactions_list_subject_bank' subject=t.subject.title bank=bank %}?from-day={{ from_day }}&from-month={{from_month}}&from-year={{from_year}}&to-day={{to_day}}&to-month={{to_month}}&to-year={{to_year}}{% if search %}&search={{search}}{% endif %}">{{ t.subject }}</a>                  
                {% else %}
                <a href="{% url 'accounting:transactions_list_subject_bank' subject=t.subject.title bank=bank %}{% if search %}?search={{search}}{% endif %}">{{ t.subject }}</a>
                {% endif %}
            </td>
            <td><span class="text-danger" dir="ltr">{{ t.amount_pay | intcomma:False }}</span></td>
            <td><span class="text-success" dir="ltr">{{ t.amount_rec | intcomma:False }}</span></td>
            <td><span class="text-light" dir="ltr">{{ t.account_level | intcomma:False }}</span></td>
            <td>
                {% if from_date_date %}
                <a href="{% url 'accounting:transactions_list_subject_bank' subject=subject bank=t.bank_account.title %}?from-day={{ from_day }}&from-month={{from_month}}&from-year={{from_year}}&to-day={{to_day}}&to-month={{to_month}}&to-year={{to_year}}{% if search %}&search={{search}}{% endif %}">{{ t.bank_account }}</a>                  
                {% else %}
                <a href="{% url 'accounting:transactions_list_subject_bank' subject=subject bank=t.bank_account.title %}{% if search %}?search={{search}}{% endif %}">{{ t.bank_account }}</a>
                {% endif %}

                
            </td>
            <td><a href="{% url 'accounting:remove_transaction' t.id %}" class="fs-6 text-danger" style="text-decoration: none;">&times;</a></td>
        </tr>
          
        {% endfor %}
    </tbody>

</table>
</div>

templates/accounting/add_payment.html
{% extends '_base.html' %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}

{% endblock head %}
{% block title %}{{ page_title }}{% endblock title %}

{% block content %}
<div class="container bg-brown " >
    <h2 class="pt-4">{{ page_title }}</h2>
    
    {% include "accounting/_accounting_header.html" %}

    <div class="row py-5" id="addPayment">
        <div class="col">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                <input type="submit" class="btn btn-light my-3" value="{% trans 'Save' %}">
            </form>        
        </div>
    </div>
        
</div>
{% endblock content %}

templates/accounting/bank_accounts_list.html
{% extends '_base.html' %}
{% load static i18n crispy_forms_tags %}
{% load humanize %}

{% block head %}

{% endblock head %}
{% block title %}{{ page_title }}{% endblock title %}

{% block content %}
<div class="container bg-brown " >
    <h2 class="pt-4">{{ page_title }}</h2>  

    {% include "accounting/_accounting_header.html" %}

    <div class="row ">
       <div class="col">
            <div class="table-responsive">  
                <table class="table table-striped table-dark">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>{% trans "Title" %}</th>
                            <th>{% trans "Current level" %}</th>
                            <th>{% trans "Initial level" %}</th>
                            <th>{% trans "Bank name" %}</th>
                            <th>{% trans "Card number" %}</th>
                            <th>{% trans "Account number" %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for b in object_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ b.title }}</td>
                            <td><span dir="ltr">{{ b.current_level | intcomma:False }}</span></td>
                            <td><span dir="ltr">{{ b.initial_level | intcomma:False }}</span></td>
                            <td>{{ b.bank_name }}</td>
                            <td>{{ b.card_number }}</td>
                            <td>{{ b.account_number }}</td>
                            
                        </tr>
                        
                        {% endfor %}
                    </tbody>

                </table>
            </div>
       </div>
    </div>
        
</div>
{% endblock content %}

templates/accounting/dashboard.html
{% extends '_base.html' %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}

{% endblock head %}
{% block title %}{{ page_title }}{% endblock title %}

{% block content %}
<div class="container bg-brown " >
    <h2 class="pt-4">{{ page_title }}</h2>    
    <div class="col">
        <a href="#" class="btn btn-outline-warning my-2">{% trans "Payment" %}</a>
        <a href="#" class="btn btn-outline-warning my-2">{% trans "Recieve" %}</a>
        <a href="#" class="btn btn-outline-warning my-2">{% trans "Bank accounts" %}</a>
        <a href="#" class="btn btn-outline-warning my-2">{% trans "Account level" %}</a>
    </div>

    <div class="row ">
       
    </div>
        
</div>
{% endblock content %}

templates/accounting/transaction_subjects_list.html
{% extends '_base.html' %}
{% load static i18n crispy_forms_tags humanize %}

{% block head %}

{% endblock head %}
{% block title %}{{ page_title }}{% endblock title %}

{% block content %}
<div class="container bg-brown " >
    <h2 class="pt-4">{{ page_title }}</h2>  
      
    {% include "accounting/_accounting_header.html" %}

    <div class="row ">
       <div class="col">
        <a href="{% url 'accounting:add_transaction_subject' %}" class="btn btn-light">{% trans "Add subject" %}</a>
        <div class="table-responsive">
            <table class="table table-stripped table-dark">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>{% trans "Subject" %}</th>
                        <th>{% trans "Transaction kind" %}</th>
                        <th>{% trans "Payment" %}</th>
                        <th>{% trans "Receive" %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for s in object_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                            <a href="{% url 'accounting:update_transaction_subject' s.id %}">{{ s.title }}</a>
                        </td>
                        <td>{{ s.get_transaction_kind_display }}</td>
                        <td>{{ s.get_subject_sum_pay | intcomma:False }}</td>
                        <td>{{ s.get_subject_sum_rec | intcomma:False }}</td>
                    </tr>
                      
                    {% endfor %}
                </tbody>
            </table>
        </div>

       </div>
         
         
       </div>
    </div>
        
</div>
{% endblock content %}

templates/accounting/transactions_list.html
{% extends '_base.html' %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}

{% endblock head %}
{% block title %}{{ page_title }}{% endblock title %}

{% block content %}
<div class="container bg-brown " >
    <h2 class="pt-4">{{ page_title }}</h2>  
      
    {% include "accounting/_accounting_header.html" %}
    <div class="my-1">
      {% if subject %}      
      <a href="{% url 'accounting:transactions_list_subject_bank' subject=subject bank=bank %}{% if search %}?search={{search}}{% endif %}" class="btn btn-sm btn-light py-0">{% trans "All" %}</a>        
      {% else %}
      <a href="{% url 'accounting:transactions_list' %}{% if search %}?search={{search}}{% endif %}" class="btn btn-sm btn-light py-0">{% trans "All" %}</a>        
      {% endif %}
      {% for month in monthes %}
      {% if subject %}      
      <a href="{% url 'accounting:transactions_list_subject_bank' subject=subject bank=bank %}{{ month.link }}{% if search %}&search={{search}}{% endif %}" class="btn btn-sm btn-light py-0">{{ month.name }}</a>        
      {% else %}
      <a href="{% url 'accounting:transactions_list' %}{{ month.link }}{% if search %}&search={{search}}{% endif %}" class="btn btn-sm btn-light py-0">{{ month.name }}</a>        
      {% endif %}
      {% endfor %}
      

      {% if from_date_date %}
        <span class="bg-secondary rounded px-1 ms-3">{{ from_date_date | date }}</span>
      {% endif %}
      {% if to_date_date %}
      <span class="bg-secondary rounded px-1">{{ to_date_date | date }}</span>
      {% endif %}
      {% if subject %}
        <span class="bg-secondary text-warning rounded px-1 ms-3">{% trans "Subject" %}: {{ subject }}</span>
      {% endif %}
      {% if bank %}
        <span class="bg-secondary text-warning rounded px-1 ms-3">{% trans "Bank" %}: {{ bank }}</span>
      {% endif %}
      {% if search %}      
          <a href="{% url 'accounting:transactions_list_subject_bank' subject=subject bank=bank %}{% if from_date_date %}?from-day={{ from_day }}&from-month={{from_month}}&from-year={{from_year}}&to-day={{to_day}}&to-month={{to_month}}&to-year={{to_year}}{% endif %}" class="bg-secondary text-warning rounded px-1 ms-3" style="text-decoration: none;">{% trans "Search" %}: {{ search }} &times;</a>        
      {% endif %}
    
    </div>

    <div class="row ">
       <div class="col">
       
         {% include "accounting/_transactions_list.html" %}
         
       </div>
    </div>
        
</div>
{% endblock content %}