ai/urls.py
from django.urls import path
from . import views

app_name = 'ai'

urlpatterns = [
    path('models-list/add/', views.AiModelAddView, name='add_model'),
    path('models-list/', views.AiModelsListView, name='ai_models_list'),
    path('test/', views.AiView, name='ai'),
        
    path('chats-list/', views.ChatListView, name='ai_chats_list'),
    path('reports/', views.ChatReportView, name='ai_chats_report'),
    path('image/new/', views.AiImageView, name='ai_image_new_chat'),
    
    path('image/<str:chat_id>/', views.AiImageView, name='ai_image_continue_chat'),  # For continuing existing chat
    
    path('edit-prompt/<int:message_id>/', views.EditPromptView, name='ai_edit_prompt'),
    path('<str:chat_id>/', views.AiCreateNewChatView, name='ai_continue_chat'),
    path('', views.AiCreateNewChatView, name='ai_create'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('bookstore/', include('bookstore.urls', namespace='bookstore')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('quizes/', include('quizes.urls', namespace='quizes')),
    path('accounting/', include('accounting.urls', namespace='accounting')),
    path('api/', include('api.urls', namespace='api')),
    path('videos/', include('videos.urls', namespace='videos')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('ai/', include('ai.urls', namespace='ai')),
    path('restaurants/', include('restaurants.urls', namespace='restaurants')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('accounts/', include('accounts.urls',)),
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('generals.urls')),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

videos/urls.py
from django.urls import path
from . import views

app_name = 'videos'

urlpatterns = [
    path('details/<uuid:uuid>/', views.video_details, name='video_details'),
    path('download/<uuid:uuid>/', views.ProtectedMediaView.as_view(), name='video_download'),
    path('stream/<uuid:uuid>/', views.VideoStreamView.as_view(), name='video_stream'),
    path('stream-atman/<uuid:uuid>/', views.AtmanVideoStreamView.as_view(), name='video_stream_atman'),
    path('upload/', views.FileUploader.as_view(), name='file_upload'), 
    path('new-upload/', views.NewFileUploader, name='new_file_upload'), 

    path('add-category/', views.AddCategoryView, name='add_category'),
    path('category/<int:category_id>/', views.VideoListView, name='category_view'),

    path('', views.VideoListView, name='video_list'),
]

videos/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.files.storage import FileSystemStorage, default_storage
import uuid 

from quizes.models import TimeStampedModel

class CustomStorage(FileSystemStorage):
    def get_available_name(self, name, max_length=None):
        # Customize the file name if needed
        return super().get_available_name(name, max_length)

custom_storage = CustomStorage(location='private_media/videos/')
    

class Category(TimeStampedModel):
    name = models.CharField(
        _('Name'),
        max_length=200,        
    )
    
    def __str__(self):
        return self.name


class Video(TimeStampedModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    category = models.ForeignKey(
        Category,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='videos'
    )
    video_file = models.FileField(
        _('Video file'), 
        upload_to='videos/',

    )
    name = models.CharField(
        max_length=200,
        default='test'
    )
    is_protected = models.BooleanField(default=False)
    website_header = models.CharField(
        max_length=200,
        default='',
        blank=True,
    )

    def get_download_info(self):
        _file = self.video_file
        # content_type = "audio/mp3"
        # download_name = self.name + ".mp3"
        return _file # content_type, download_name, 
    
    def __str__(self):
        return self.name
    
    def get_size(self):
        if self.is_protected:
            return custom_storage.size(self.video_file.name)
        else:
            return self.video_file.size
    
    def get_path(self):
        if self.is_protected:
            return custom_storage.path(self.video_file.name)
        else:
            return self.video_file.path
        
    def save(self, *args, **kwargs):
        # if self.website_header:
        #     self.is_protected = True
        if self.is_protected:
            self.video_file.storage = custom_storage
        else:
            self.video_file.storage = default_storage
        super().save(*args, **kwargs)
  

videos/forms.py
from django import forms

from .models import Video, Category

class VideoUploadForm(forms.Form):
    your_file = forms.FileField()
    name = forms.CharField(max_length=150)

class VideoUploadNewForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['name', 'video_file', 'category', 'website_header']


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

videos/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseForbidden, HttpResponse
from django.views.generic import View
from django.conf import settings
from rest_framework.permissions import IsAdminUser
import os
from django.contrib.admin.views.decorators import staff_member_required


from rest_framework.parsers import FileUploadParser
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from .serializers import YourFileSerializer
from .forms import VideoUploadForm, VideoUploadNewForm, CategoryForm
import logging

from django.http import StreamingHttpResponse
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.views import View
import mimetypes


from .models import Video, Category
from .tasks import upload_file




logger = logging.getLogger('videos')  # Use the logger name defined in LOGGING


@staff_member_required
def VideoListView(request, category_id=None):
    category = None
    context = dict(
        page_title='All videos'
    )
    videos = Video.objects.all().order_by('-created')
    if category_id:
        try:
            category = Category.objects.get(id=category_id)
        except: 
            pass
    if category:
        videos = videos.filter(category=category)
        context['page_title'] = f"Category: {category.name}"

    context['videos'] = videos
    return render (
        request,
        'videos/videos_list.html',
        context
    )



class ProtectedMediaView(View):
    def get(self, request, uuid):
        # Check user permissions or any other access control logic here
        if not request.user.has_perm('can_access_media'):
            return HttpResponseForbidden("You don't have permission to access this media.")

        video = Video.objects.get(id=uuid)

        # Construct the full path to the media file
        media_path = os.path.join(settings.MEDIA_ROOT, video.name)


        # Serve the file
        with open(video.video_file.path, 'rb') as file:
            response = HttpResponse(file.read(), content_type='application/octet-stream')

        return response


@staff_member_required
def video_details(request, uuid):
    video = Video.objects.get(id=uuid)
    return render(
        request,
        'videos/video_details.html',
        {
            'video':video,
        }
    )




def restrict_referer(request, website):
    # Check if the request has a referer
    referer = request.META.get('HTTP_REFERER')
    
    # Define the allowed website
    allowed_website = website
    if website == '':
        return True
    
    # Check if the referer matches the allowed website
    if referer and referer.startswith(allowed_website):
        # If the referer matches, allow the request to continue
        return True
    else:
        # If the referer doesn't match, return a forbidden response
        return False


class VideoStreamView(View):
    def get(self, request, *args, **kwargs):
        video = Video.objects.get(id=kwargs['uuid'])
        website = video.website_header

        
        if restrict_referer(request, website):
            referer = request.META.get('HTTP_REFERER')

            video_path = video.get_path()
            # Set the correct content type
            content_type, encoding = mimetypes.guess_type(video_path)
            content_type = content_type or 'application/octet-stream'

            # Set response headers to prevent direct download
            response = StreamingHttpResponse(self.file_iterator(video_path), content_type=content_type)
            response['Content-Disposition'] = 'inline; filename="video.mp4"'  # Set filename for inline display
            if referer and ('computermuseum.ir' in referer or 'atmancenter.org' in referer):
                response['X-Frame-Options'] = 'ALLOW-FROM ' + referer
            return response
            # return HttpResponse("Allowed")
        else:
            # Return a forbidden response
            return HttpResponseForbidden()


    def file_iterator(self, file_path, chunk_size=8192):
        with default_storage.open(file_path, 'rb') as f:
            while True:
                data = f.read(chunk_size)
                if not data:
                    break
                yield data

class AtmanVideoStreamView(View):
    def get(self, request, *args, **kwargs):
        video = Video.objects.get(id=kwargs['uuid'])
        website = video.website_header

        referer = request.META.get('HTTP_REFERER')
        
        # Log the referer
        logger.debug(f"HTTP_REFERER: {referer}")
        
        if referer and (
            referer.startswith('https://atmancenter.org/') or 
            referer.startswith('https://rahimagha.ir/')
        ):
        
            video_path = video.get_path()
            # print(video_path)
            # Set the correct content type
            content_type, encoding = mimetypes.guess_type(video_path)
            content_type = content_type or 'application/octet-stream'

            # Set response headers to prevent direct download
            response = StreamingHttpResponse(self.file_iterator(video_path), content_type=content_type)
            response['Content-Disposition'] = 'inline; filename="video.mp4"'  # Set filename for inline display
            # set the header for request from specific origin
            response['X-Frame-Options'] = 'ALLOW-FROM https://atmancenter.org'
            
            response['X-Content-Type-Options'] = 'nosniff'
            # This will only allow requests from atmancenter.org to access your video content.
            response['Access-Control-Allow-Origin'] = 'https://atmancenter.org'
            # allow methods
            response['Access-Control-Allow-Methods'] = 'GET, OPTIONS'
            # specifies the allowed headers for the request
            response['Access-Control-Allow-Headers'] = 'Origin, Content-Type, Accept, Range'
            # specifies the headers that are exposed to the client.
            response['Access-Control-Expose-Headers'] = 'Content-Length, Content-Range'
            return response
            # return HttpResponse("Allowed")
        else:
            # Return a forbidden response
            return HttpResponseForbidden()


    def file_iterator(self, file_path, chunk_size=8192):
        with default_storage.open(file_path, 'rb') as f:
            while True:
                data = f.read(chunk_size)
                if not data:
                    break
                yield data



class FileUploader(APIView):
    permission_classes = [IsAdminUser]
    parser_classes = (FileUploadParser,)
    def get(self, request, *args, **kwargs):
        form = VideoUploadForm()
        return render (request, 'videos/video_upload.html', {'form': form})
    def post(self, request, *args, **kwargs):
        file_serializer = YourFileSerializer(data=request.data)

        if file_serializer.is_valid():
            new_file = file_serializer.validated_data['your_file']
            
            vid = Video.objects.create(
                video_file=new_file,
                name=new_file.name
            )
            response = Response({'video_id': vid.id}, status=status.HTTP_201_CREATED)
            response['Content-Disposition'] = f'attachment; filename="{new_file.name}"'
            # response['Content-Disposition'] = f'attachment; filename="{your_file.name}"'
            return response
        return Response(file_serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    


class FileUploader(APIView):
    permission_classes = [IsAdminUser]
    parser_classes = (FileUploadParser,)

    def get(self, request, *args, **kwargs):
        form = VideoUploadForm()
        return render(request, 'videos/video_upload.html', {'form': form})

    def post(self, request, *args, **kwargs):
        file_serializer = YourFileSerializer(data=request.data)
        print(file_serializer)
        # print (request.data)
        if file_serializer.is_valid():
            print('hi')
            new_file = file_serializer.validated_data['your_file']
            name = file_serializer.validated_data['name']
            print(name, new_file.name)
            vid = Video.objects.create(
                video_file=new_file,
                name=new_file.name
            )
            response = Response({'video_id': vid.id}, status=status.HTTP_201_CREATED)
            response['Content-Disposition'] = f'attachment; filename="{name}"'
            return response
        else: 
            print(file_serializer.errors)
        # print(response)
        # print(response.items())
        return Response(file_serializer.errors)
    

@staff_member_required
def NewFileUploader(request):
    if request.method == 'POST':
        form = VideoUploadNewForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            new_video = form.save(commit=False)
            file = new_video.video_file
            # it wirtes file in root of project
            # handle_uploaded_file(file)
            new_video.save()
            # upload_file.delay(new_video.video_file, new_video.name, new_video.category)
            # add sample comments
            return redirect ('videos:video_list')
    else:
        form = VideoUploadNewForm()
    return render(
        request, 
        'videos/video_upload.html', 
        {'form': form},     
    )


def handle_uploaded_file(f):
    with open(f.name, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)


@staff_member_required
def AddCategoryView(request):
    if request.method == 'POST':
        form = CategoryForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect ('videos:video_list')
    else:
        form = CategoryForm()

    context = dict(
        form=form
    )
    return render(
        request,

templates/videos/_video_base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

        {% if LANGUAGE_CODE == 'fa' %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css" integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous">
        <link href="{% static 'css/farsi.css' %}" rel="stylesheet">
        {% endif %}
        {% if LANGUAGE_CODE == 'en' %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        {% endif %}
        {% block head %}
          
        {% endblock head %}
    </head>
    <body>
        <div class="container-fluid">
            {% block content %}
            
            {% endblock content %}
        </div>
        <script async src="https://kit.fontawesome.com/da37b563d5.js" crossorigin="anonymous"></script>
        {% block script %}
          
        {% endblock script %}
    </body>
</html>

templates/videos/add_category.html
{% extends "videos/_video_base.html" %}

{% load crispy_forms_tags i18n %}

{% block content %}
<h1>{% trans "Add category" %}</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{ form | crispy }}
    <input type="submit" name="" id="" class="btn btn-success my-2" value="{% trans 'Submit' %}">
</form>


{% endblock content %}

templates/videos/video_details.html
{% extends "videos/_video_base.html" %}


{% block content %}
{% comment %}
<video src="{% url 'videos:video_details' video.id %}" controls>
  {{ video.id }}
</video>  
{% endcomment %}
<video controls>
  <source src="{{ video.video_file.url }}" type="video/mp4">
  <source src="{{ video.video_file.url }}" type="video/ogg">
  <source src="{{ video.video_file.url }}" type="video/webm">
</video>

{% endblock content %}

templates/videos/video_upload.html
{% extends "videos/_video_base.html" %}

{% load crispy_forms_tags i18n %}
{% block content %}

<h1>Video uploader </h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form | crispy }}
    <input type="submit" value="{% trans 'Upload' %}" class="btn btn-success my-2">
</form>
{% endblock content %}

templates/videos/videos_list.html
{% extends "videos/_video_base.html" %}

{% load humanize i18n %}

{% block content %}

<h1>{{ page_title }}</h1>


<div>
    <a href="{% url 'videos:video_list' %}" class="btn btn-outline-success">Video list</a>
    <a href="{% url 'videos:new_file_upload' %}" class="btn btn-outline-success">Upload video</a>
    <a href="{% url 'videos:add_category' %}" class="btn btn-outline-success">Add category</a>
    
    {% if request.user.is_superuser %}
    <a href="{% url 'videos:file_upload' %}" class="btn btn-outline-success">rest</a>      
    {% endif %}
</div>
<div class="table-responsive">
    
    <table class="table table-stripped">
        <thead>
            <th>#</th>
            <th>name</th>
            <th>Is protected</th>
            <th>Website</th>
            <th>Date</th>
            
            <th>Download</th>
            <th>Size</th>
            <th>Stream</th>
            <th>Stream 2</th>
            <th>category</th>
            <thead>iFrame</th>
    </thead>
    <tbody>
        {% for video in videos %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ video.name }}</td>
            <td>{{ video.is_protected }}</td>
            <td>{{ video.website_header }}</td>
            <td>{{ video.created }}</td>
            {#<td><a href="{% url 'videos:video_details' video.id %}" target="_blank">{{ video.id }}</a></td>#}
            <td>{% if not video.is_protect %}<a href="{{ video.video_file.url  }}" download="">{{ video.video_file.name }}</a>{% endif %}</td>
            <td><span>{{ video.get_size | filesizeformat }}</span></td>
            <td><a href="{% url 'videos:video_stream' video.id  %}" target="_blank">Stream</a></td>
            <td><a href="{% url 'videos:video_stream_atman' video.id  %}" target="_blank">Stream atman</a></td>
            <td>
                {% if video.category %}
                
                <a href="{% url 'videos:category_view' video.category.id %}">
                    {{ video.category }}
                </a>
                {% endif %}
            </td>
            
            <td>
                <textarea id="{{ video.video_file.name }}"><iframe src="https://rahimagha.ir{{ video.video_file.url }}" title="{{ video.name }}" autoplay="false" allow="fullscreen"  referrerpolicy="no-referrer" height="600px" width="800px" style="border:none;"></iframe></textarea>
            </td>
            <td>
                <!-- The button used to copy the text -->
                <button onclick="myFunction(`{{ video.video_file.name }}`)" class="btn btn-sm btn-secondary">
                    <i class="fa-regular fa-copy"></i>
                </button>
            </td>
            
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>


{% endblock content %}

{% block script %} 
<script>
function myFunction(v_name) {
    // Get the text field
    var copyText = document.getElementById(v_name);
    
    // Select the text field
    copyText.select();
    copyText.setSelectionRange(0, 99999); // For mobile devices
    
    // Copy the text inside the text field
    navigator.clipboard.writeText(copyText.value);
    
    // Alert the copied text
    alert("iFrame code copied: " + v_name);
} 

</script>
{% endblock script %} 