ai/urls.py
from django.urls import path
from . import views

app_name = 'ai'

urlpatterns = [
    path('models-list/add/', views.AiModelAddView, name='add_model'),
    path('models-list/', views.AiModelsListView, name='ai_models_list'),
    path('test/', views.AiView, name='ai'),
        
    path('chats-list/', views.ChatListView, name='ai_chats_list'),
    path('reports/', views.ChatReportView, name='ai_chats_report'),
    path('image/new/', views.AiImageView, name='ai_image_new_chat'),
    
    path('image/<str:chat_id>/', views.AiImageView, name='ai_image_continue_chat'),  # For continuing existing chat
    
    path('edit-prompt/<int:message_id>/', views.EditPromptView, name='ai_edit_prompt'),
    path('<str:chat_id>/', views.AiCreateNewChatView, name='ai_continue_chat'),
    path('', views.AiCreateNewChatView, name='ai_create'),
]

contacts/urls.py
from django.urls import path
from . import views

app_name = 'contacts'

urlpatterns = [
    path('', views.contacts, name='contacts')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('bookstore/', include('bookstore.urls', namespace='bookstore')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('quizes/', include('quizes.urls', namespace='quizes')),
    path('accounting/', include('accounting.urls', namespace='accounting')),
    path('api/', include('api.urls', namespace='api')),
    path('videos/', include('videos.urls', namespace='videos')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('ai/', include('ai.urls', namespace='ai')),
    path('restaurants/', include('restaurants.urls', namespace='restaurants')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('accounts/', include('accounts.urls',)),
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('generals.urls')),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

generals/urls.py
from django.urls import path
from . import views

app_name = "generals"

urlpatterns = [
    path('geolocation/<str:ip>/', views.GetCountryFromIP.as_view(), name="geo"),
    path('no-access/', views.NoAccessView, name='no_access'),
    path('', views.HomeView, name='home'),
]

projects/urls.py
from django.urls import path 
from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.ProjectView.as_view(), name='projects')
]

quizes/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'quizes'

urlpatterns = [
    path('questions/create/', login_required(views.QuestionCreateView.as_view()), name='question_create' ),
    path('questions/update/<int:pk>/', login_required(views.QuestionUpdateView.as_view()), name='question_update' ),
    path('questions/list/', login_required(views.QuestionListView.as_view()), name='questions_list' ),
    
    path('compliment/create/', login_required(views.ComplimentCreateView.as_view()), name='compliment_create' ),
    path('compliment/update/<int:pk>/', login_required(views.ComplimentUpdateView.as_view()), name='compliment_update' ),
    path('compliment/list/', login_required(views.ComplimentListView.as_view()), name='compliment_list' ),

    path('my-quiz/result/<uuid:pk>/', views.QuizResultView, name='my_quiz_result' ),    
    path('my-quiz/<str:error>/<uuid:quiz_pk>/<int:step>/', views.NewMyQuizProccessView, name='my_quiz_proccess_error' ),
    path('my-quiz/<uuid:quiz_pk>/<int:step>/', views.NewMyQuizProccessView, name='my_quiz_proccess' ),
    path('my-quiz/', views.MyQuizView, name='my_quiz' ), #also uses for start a quiz

    # reports
    path('questions/update-report/', views.QuestionCorrectRateUpdate, name="update_question_report"),

]

templates/_base.html
{% load static i18n %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}" {% if LANGUAGE_CODE == 'fa' %}dir="rtl"{% else %}dir="ltr"{% endif %}>
    <head>

        {% include "_general_head.html" %}
        
        {# ================================================================================= #}
        {# css files                                                                         #}
        {# ================================================================================= #}
        {% if LANGUAGE_CODE == 'fa' %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css" integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous">
        <link href="{% static 'css/farsi.css' %}" rel="stylesheet">
        {% endif %}
        {% if LANGUAGE_CODE == 'en' %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        {% endif %}

        <link rel="stylesheet" href="{% static 'css/codehilite.css' %}">
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
      
    </head>
    <body>
        <header>
                {% include '_navbar.html' %}
                {% comment %} 
                {% if request.user.is_staff %}
                {% include '_staff_navbar.html' %}
                {% endif %}
                {% endcomment %}
                
                {% include '_messages.html' %}
        </header>
        <main>         
          
            {% block content %}{% endblock content%}            

        </main>
        
        <footer>
            {% include "_footer.html" %}
        </footer>    
        <script async src="https://kit.fontawesome.com/da37b563d5.js" crossorigin="anonymous"></script>
        {% comment %} Bootstrap V4 {% endcomment %}
        {% comment %} <script async src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> {% endcomment %}
        {% comment %} <script async src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script> {% endcomment %}
        {% comment %} <script async src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script> {% endcomment %}
        <!-- bundle for bootstrap -->
        <script async src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

        
      {% block script %}
      {% endblock %}
    </body>
    
</html>
    

templates/_base_restaurants.html
{% load static i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}" {% if LANGUAGE_CODE == 'fa' %}dir="rtl"{% else %}dir="ltr"{% endif %}>

    <head>
        {% include "_general_head.html" %}
        
        
        {% if LANGUAGE_CODE == 'fa' %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css" integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous">
        {#<link href="{% static 'css/farsi.css' %}" rel="stylesheet">#}
        {% endif %}
        {% if LANGUAGE_CODE == 'en' %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        {% endif %}
        <link rel="stylesheet" href="{% static 'css/codehilite.css' %}">


        {#<link href="{% static 'css/base.css' %}" rel="stylesheet">#}
        
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
            integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
            crossorigin=""/>
    </head>
    <body>
        <header>
            {% comment %} 
                {% include '_navbar.html' %}
                {% if request.user.is_staff %}
                {% include '_staff_navbar.html' %}
                {% endif %}
            {% endcomment %}
                
                {% include '_messages.html' %}
        </header>
        <main>         
          
            {% block content %}{% endblock content%}            

        </main>
        
        <footer>

        </footer>    
        <script async src="https://kit.fontawesome.com/da37b563d5.js" crossorigin="anonymous"></script>
        
        <!-- bundle for bootstrap -->
        <script async src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


        <!-- {# Leaflet JS (needs to be loaded before your map script) #} -->
        <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
        integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
        crossorigin=""></script>

    
        
      {% block script %}
      {% endblock %}
    </body>
    
</html>
    

templates/_footer.html
{% load i18n %}
{% load static %}

<div class="p-2 container-fluid bg-brown border-top">
    <div class="row p-2">
     
      <div class="col-md-6 text-light px-4">
        <p class="lead">{% trans 'Rahim Aghareb' %}</p>
        <p>{% trans "I am a software designer and developer. I have more than 10 years experiences in website design and now I am developing web-applications based on django and python." %}</p>

        
        <!-- <p>
          <a href="mailto:info@irancomputermuseum.org">info@irancomputermuseum.org/</a>
        </p> -->
      </div>
      

      <div class="col-md-6 text-light px-4">
        <p class="lead">{% trans "Links" %}</p>

        <div class="d-flex justify-content-start w-75">          
          <a href="https://github.com/rahimz/" target="_blank" rel="nofollow">
            <img src="{% static 'img/github-mark-white.png' %}" width="30rem" height="auto"  alt="Rahim github logo">            
          </a>
          <a href="https://www.linkedin.com/in/rahim-aghareb-5714bb85/" target="_blank" rel="nofollow">            
            <img src="{% static 'img/In-White-96.png' %}" width="30rem" height="auto" class="ms-4"  alt="Rahim linkdin logo">            
          </a>
        </div>
        <p class="mt-3"><a href="{% url 'contacts:contacts' %}">{% trans "Contact me" %}</a></p>        

      </div>
    </div>
  </div>

</div>

templates/_messages.html
{% if messages %}    
    {% for message in messages %}    
    <div  class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message|safe }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
            {% comment %} <span aria-hidden="true">&times;</span> {% endcomment %}
        </button>
    
    </div>

    {% endfor %}


{% endif %}

{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
    $("#alert").fadeTo(4000, 500).slideUp(500, function(){
        $("#success-alert").slideUp(500);
    });
</script>
{% endblock script %}

templates/_navbar.html
{% load i18n %}
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-brown border-bottom shadow" id="top">
  <div class="container-fluid py-1">
    <a class="navbar-brand" href="{% url 'generals:home' %}">
      <img src="{% static 'img/rahimagha_logo_sq.png' %}" alt="RahimAgha logo" width="70px" height="auto">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link {% if mainNavSection == 'home' %}active{% endif %}" href="{% url 'generals:home' %}">{% trans "Home" %}</a>
        </li>

        <li class="nav-item">
          <a class="nav-link {% if mainNavSection == 'projects' %}active{% endif %}" href="{% url 'generals:home' %}#projects">{% trans "Projects" %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if mainNavSection == 'resume' %}active{% endif %}" href="{% url 'generals:home' %}#resume">{% trans "Resume" %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if mainNavSection == 'services' %}active{% endif %}" href="{% url 'bookstore:bookstore' %}">{% trans "Bookstore" %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if mainNavSection == 'contacts' %}active{% endif %}" href="{% url 'contacts:contacts' %}">{% trans "Contact me" %}</a>
        </li>
        {% if request.user.is_authenticated %}
        <li>
          <a class="nav-link {% if mainNavSection == 'ai' %}active{% endif %}" href="{% url 'ai:ai_create' %}">{% trans "AI" %}</a>
        </li>

        {% endif %}
        {% comment %} Show the quiz tab in farsi {% endcomment %}
        {% if LANGUAGE_CODE == 'fa' %}
        <li class="nav-item">
          <a class="nav-link {% if mainNavSection == 'quizes' %}active{% endif %}"
          {% if request.user.is_superuser %}
          href="{% url 'quizes:questions_list' %}"
          {% else %}
          href="{% url 'quizes:my_quiz' %}"
          {% endif %}
          >
          {% trans "Quizes" %}
        </a>
        </li>
        {% endif %}

        {% if request.user.is_superuser %}
        <li class="nav-item">
          <a href="{% url 'accounting:transactions_list' %}" class="nav-link {% if mainNavSection == 'accounting' %}active{% endif %}">{% trans 'Accounting' %}</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'admin:index' %}" class="nav-link ">{% trans 'Admin' %}</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'rosetta-old-home-redirect' %}" class="nav-link ">Rosetta</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'restaurants:res_home' %}" class="nav-link ">{% trans "Restaurants" %}</a>
        </li>

        {% endif  %}

        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        <li class="nav-item">
          {% if LANGUAGE_CODE == 'en' %}
            <form action="{% url 'set_language' %}" method="post" class="me-2">
                {% csrf_token %}
                <input name="next" type="hidden" value="{{ request.get_full_path|slice:'3:' }}">
                <input name="language" type="hidden" value="fa">
                <a href="#" onclick="this.closest('form').submit();" class="nav-link">fa</a>
            </form>
            {% elif LANGUAGE_CODE == 'fa' %}
            <form action="{% url 'set_language' %}" method="post">
                {% csrf_token %}
                <input name="next" type="hidden" value="{{ request.get_full_path|slice:'3:' }}">
                <input name="language" type="hidden" value="en">
                <a href="#" onclick="this.closest('form').submit();" class="nav-link ">en</a>
            </form>
            {% endif %}
        </li>
      </ul> 
      {% if request.user.is_authenticated %}
        <span class="navbar-text text-white ms-2">
            Welcome, {{ request.user.username }}!
        </span>
      {% endif %}


        
      <div class="ms-3">
        {% if request.user.is_authenticated %}
        <div>
          <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn"><i class="fas fa-sign-out text-light"></i></button>
          </form>
        </div>
        {% else %}
        <a href="{% url 'login' %}" class="btn"><i class="fas fa-sign-in-alt text-light"></i></a>
        {% endif %}        
        
      </div>
    
    </div>
  </div>
</nav>

  {% block script %}
  <script>

    </script>
  {% endblock script %}

templates/_pagination.html
{% load i18n %}
<div class="pagination d-flex justify-content-center">
  <p class="step-links ">
    {% if page.has_previous %}
    <a href="?page=1" class="btn btn-outline-success m-3">&laquo; {% trans 'first' %}</a>
    <a href="?page={{ page.previous_page_number }}" class="btn btn-outline-success m-3">  {% trans 'Previous' %}</a>
    {% endif %}
    <span class="current">
      {% trans 'Page' %} {{ page.number }} {% trans 'of' %} {{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}" class="btn btn-outline-success m-3">{% trans 'Next' %}</a>
    <a href="?page={{ page.paginator.num_pages }}" class="btn btn-outline-success m-3">{% trans 'last' %} &raquo;</a>
    {% endif %}
  </p>
</div>

templates/access_denied.html
{% extends "_base.html" %}
    
{% block title %}
  No access
{% endblock title %}

{% block content %}
<div class="container text-light text-center">
    <div class="row">        
        <div class="col-md-11">
            <div class="my-5">
                <h4>You do not have access to this page</h4>
            </div>
    </div>
    
    
</div>
  
{% endblock content %}

templates/home.html
{% extends '_base.html' %}
{% load i18n %}
{% load static %}

{% block head %}
<style>
    .cropped {
        width: 300px; 
        height: 300px; 
        object-fit: cover;
        object-position: 100% 100%; 
    }
</style>
{% endblock head %}
{% block title %}{{ page_title }}{% endblock title %}

{% block content %}
<div class="container bg-brown " >
    <!-- <div class="row">
        <form action="">
            <div class="form-check form-switch">
                <input class="form-check-input" type="checkbox" id="SwitchNight" name="SwitchNight">
                <label class="form-check-label" for="SwitchNight">Night</label>
                <input type="submit" value="submit">
              </div>
        </form>
    </div> -->
    <h2 class="pt-4">{% trans "Bookstore solution" %}</h2>
    <div class="row" id="bookstore">
        <div class="col-md-12">
            <div class=" p-4">
                <div >
                    <a href="{% url 'bookstore:bookstore' %}" class="" style=" text-decoration: None;">
                        <img src="{% static 'img/staff_home_bookstore.png' %}" class="rounded" alt="bookstore home page" width="100%" height="auto">
                    </a>
                </div>
                <h4 class="pt-3">{% trans "What is bookstore solution?" %}</h4>
                <p>
                    {% trans "The bookstore solution is an online sulotin for anyone who sells books" %}. {% trans "In this software you can register invoices, purchases and also you could have an online shop" %}. 
                    <br>
                    {% trans "With this software you do not need any other cashier solution" %}
                </p>
                <h4>{% trans "Main features" %}</h4>
                <ul>
                    <li>{% trans "It is really flexible and can be just be tailored to your needs" %}</li>
                    <li>{% trans "Each book could have 7 variaion-stock" %}</li>
                    <li>{% trans "You could control the whole proccess of purchase, sales and change in variation prices" %}</li>
                    <li>{% trans "There a robust search engine in the system for online user and staffs" %}</li>
                    <li>{% trans "Many kind of permissions and access levels could be defined in the system for staffs" %}</li>
                </ul>
                <div>
                    <a href="{% url 'bookstore:bookstore' %}" class="btn-special px-3 py-2">{% trans "More details" %}...</a>
                </div>
            </div>
        </div>

    </div>
    <div class="row py-5" id="projects">
        
        <h2>{% trans "Projects" %} <a class="ms-5 lead fw-bold fs-4 " href="#top" style="text-decoration: none;">&#8593</a></h2>
        <div class="col-md-6">
            <div class="  text-center p-4">
                <div class="text-center image-projects-container" >
                    <img class="rounded image-projects" src="{% static 'img/ketabedamavand.jpg' %}" alt="Ketabe Damavand logo" >
                </div>
                <h4 class="mt-3" >Ketabedamavand.com</h4>
                <p>
                    {% trans "Ketabe Damavand is a bookstore in Tehran and also has online channels for introduce and sell books" %}. 
                   <br> {% trans "The Ketabedamavand.com is started in 2021 and now it has more than 30,000 products with about 3,000 clients and 10 staff" %}.
                </p>
                <a href="https://ketabedamavand.com" target="_blank" class="btn-special">{% trans "Website" %}  &#8599</a>

            </div>                
        </div>          
        <div class="col-md-6">
            <div class="  text-center p-4">
                <div class="text-center image-projects-container">
                    <img class="rounded bg-light image-projects" src="{% static 'img/computermuseum2.png' %}" alt="Iran computer museum logo" >
                </div>
                <h4 class="mt-3" >Computermuseum.ir</h4>
                <p>
                    {% trans "Computer museum is the first Iran computer museum and the website has Exhibition, Timeline, Science Tour and Oral History project" %}.
                    {% trans "In the backend the website support a standard system of archival items record keeping" %}.
                </p>
                <a href="http://computermuseum.ir" target="_blank" class="btn-special">{% trans "Website" %} &#8599</a>
            </div>                
        </div>
    </div>
    <div class="row my5 text-center">
        <h3>
            <a href="{% url 'projects:projects' %}" class="btn-special">{% trans "Other projects" %}</a>
        </h3>
    </div>

    <div class="row py-5" id="resume">
        <div class="col">            
                <h2>{% trans "Resume" %} <a class="ms-5 lead fw-bold fs-4 " href="#top" style="text-decoration: none;">&#8593</a></h2>             
            <p>
                {% trans "Rahim Aghareb (1979) Python/Django developer" %}            
                <br>
                {% trans "I develop small size websites with Python and Django in back-end and enhance them with HTML, CSS, Bootstrap and JavaScript in front-end. Then I publish them on Linux VPS" %}.                 
            </p>
            <h4>{% trans "Some of the projects" %}:</h4>
            <ul>
                <li>rahimagha.ir (2021): {% trans "A mini online shop now change to this site (as developer)" %}</li>
                <li><a target="_blank" rel="nofollow" href="http://Khanemon.com">Khanemon.com</a> (2019-2021): {% trans "An Online marketplace for interior products (as project manager)" %}</li>
                <li><a target="_blank" rel="nofollow" href="http://Sirsoor.com">Sirsoor.com</a> (2017-2019): {% trans "cooking weblog (as content manager and photographer)" %}</li>
                <li><a target="_blank" rel="nofollow" href="http://Cookiran.ir">Cookiran.ir</a> (2016-2017) {% trans "One of the biggest chain confectionery in Iran (as project manager)" %}</li>
                <li><a target="_blank" rel="nofollow" href="http://Nahantavan.ir">Nahantavan.ir</a> (2017-2018): {% trans "A platform for disabled job seekers (as project manager)" %}</li>
                <li><a target="_blank" rel="nofollow" href="http://Elvatech.ir">Elvatech.ir</a> (2019): {% trans "Company website (as developer)" %}</li>
                <li><a target="_blank" rel="nofollow" href="http://Gineau.com">Gineau.com</a> (2019): {% trans "A website for hand-made leather products (as developer)" %}</li>
            </ul>
            <a href="{% static 'resume/CV_wr_dev_en_2022_2.pdf' %}" class="btn-special" download>{% trans "Resume" %} <span class="small" dir="ltr" >.pdf</span> &#8595</a>

            <h4 class="mt-3">{% trans "Voluntary Jobs" %}:</h4>
            <h5>{% trans "Django Girls" %}</h5>
            <p><a href="https://djangogirls.org/">Django Girls</a> {% trans "is a non-profit organization to help people to organize free, one-day programming workshop." %}
                <br>
                {% trans "I was responsible for the first Django Girls workshop in Tehran" %} <a href="https://djangogirls.org/en/tehran/">Django girls Tehran(2018)</a>
                <br>
                {% trans "Now responsible for Farsi translation of Django Girls tutorial" %} <a href="https://tutorial.djangogirls.org/fa/"> &#8599</a>
            </p>
            
        </div>
    </div>
        
</div>
{% endblock content %}