ai/urls.py
from django.urls import path
from . import views

app_name = 'ai'

urlpatterns = [
    path('models-list/add/', views.AiModelAddView, name='add_model'),
    path('models-list/', views.AiModelsListView, name='ai_models_list'),
    path('test/', views.AiView, name='ai'),
        
    path('chats-list/', views.ChatListView, name='ai_chats_list'),
    path('reports/', views.ChatReportView, name='ai_chats_report'),
    path('image/new/', views.AiImageView, name='ai_image_new_chat'),
    
    path('image/<str:chat_id>/', views.AiImageView, name='ai_image_continue_chat'),  # For continuing existing chat
    
    path('edit-prompt/<int:message_id>/', views.EditPromptView, name='ai_edit_prompt'),
    path('<str:chat_id>/', views.AiCreateNewChatView, name='ai_continue_chat'),
    path('', views.AiCreateNewChatView, name='ai_create'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('bookstore/', include('bookstore.urls', namespace='bookstore')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('quizes/', include('quizes.urls', namespace='quizes')),
    path('accounting/', include('accounting.urls', namespace='accounting')),
    path('api/', include('api.urls', namespace='api')),
    path('videos/', include('videos.urls', namespace='videos')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('ai/', include('ai.urls', namespace='ai')),
    path('restaurants/', include('restaurants.urls', namespace='restaurants')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('accounts/', include('accounts.urls',)),
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('generals.urls')),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

quizes/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'quizes'

urlpatterns = [
    path('questions/create/', login_required(views.QuestionCreateView.as_view()), name='question_create' ),
    path('questions/update/<int:pk>/', login_required(views.QuestionUpdateView.as_view()), name='question_update' ),
    path('questions/list/', login_required(views.QuestionListView.as_view()), name='questions_list' ),
    
    path('compliment/create/', login_required(views.ComplimentCreateView.as_view()), name='compliment_create' ),
    path('compliment/update/<int:pk>/', login_required(views.ComplimentUpdateView.as_view()), name='compliment_update' ),
    path('compliment/list/', login_required(views.ComplimentListView.as_view()), name='compliment_list' ),

    path('my-quiz/result/<uuid:pk>/', views.QuizResultView, name='my_quiz_result' ),    
    path('my-quiz/<str:error>/<uuid:quiz_pk>/<int:step>/', views.NewMyQuizProccessView, name='my_quiz_proccess_error' ),
    path('my-quiz/<uuid:quiz_pk>/<int:step>/', views.NewMyQuizProccessView, name='my_quiz_proccess' ),
    path('my-quiz/', views.MyQuizView, name='my_quiz' ), #also uses for start a quiz

    # reports
    path('questions/update-report/', views.QuestionCorrectRateUpdate, name="update_question_report"),

]

quizes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView, ListView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.postgres.search import SearchVector
# from django.db.models import Sum, Count
from django.contrib.auth.decorators import login_required
import random 
import requests
from PIL import Image as IMG
from io import BytesIO
from django.core.files import File
from django.contrib.admin.views.decorators import staff_member_required
from bs4 import BeautifulSoup


from .models import Question, Quiz, QuizResponse, Compliment

# staff access
class QuestionCreateView(LoginRequiredMixin, CreateView):
    model = Question
    template_name = 'quizes/question_create.html'
    fields = [
        'description', 'correct', 'wrong_1', 'wrong_2', 'wrong_3',
        'difficulty', 'link', 'published' 
    ]
    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            return redirect('generals:no_access')
        return super().dispatch(request, *args, **kwargs)

    # success_url = '/quizes/questions/list/'
    def get_success_url(self):
        return reverse ('quizes:questions_list')
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = _('Create question')
        context['mainNavSection'] = 'quizes' 
        return context


class QuestionUpdateView(LoginRequiredMixin, UpdateView):
    model = Question
    template_name = 'quizes/question_create.html'
    fields = [
        'description', 'correct', 'wrong_1', 'wrong_2', 'wrong_3',
        'difficulty', 'link', 'published'           
    ]
    # superuser access
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            return redirect('generals:no_access')
        return super().dispatch(request, *args, **kwargs)
    
    # success_url = '/quizes/questions/list/'
    def get_success_url(self):
        return reverse ('quizes:questions_list')
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = _('Update question')
        context['mainNavSection'] = 'quizes' 
        return context


class QuestionListView(LoginRequiredMixin, ListView):
    queryset = Question.objects.all()
    model = Question
    template_name = 'quizes/question_list.html'
    ordering = ('difficulty', )

    # superuser access
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            return redirect('generals:no_access')
        return super().dispatch(request, *args, **kwargs)
    
    def get_queryset(self):
        if self.request.GET.get('search'):

            return super().get_queryset().annotate(
            search=SearchVector('description', 'correct', 'wrong_1', 'wrong_2', 'wrong_3'),
                ).filter(search=self.request.GET.get('search'))

        return super().get_queryset()
       
    def get_context_data(self, **kwargs):
        
        context = super().get_context_data(**kwargs)
        context['page_title'] = _('Questions list')
        context['mainNavSection'] = 'quizes'
        if self.request.GET.get('search'):
            context['query'] = self.request.GET.get('search')
   
        return context

def MyQuizView(request, pk=None):
    # print(request.GET.get('start'), type(request.GET.get('start')))
    quiz = None

    #  set the quiz difficulty
    quiz_difficulty = '1'
    if request.GET.get('diff') == '2':
        quiz_difficulty = '2'
    elif request.GET.get('diff') == '3':
        quiz_difficulty = '3'

    # if request.GET.get('start') == 'True' and request.session.get('quiz_completed', True):
    if request.GET.get('start') == 'True':
        questions_id = SelectQuestion(quiz_difficulty)
        questions = Question.objects.filter(id__in=questions_id)
        
        # if any old and unfinished quiz be in the session it should be finished first
        old_quiz_id = request.session.get('quiz_id', None)
        old_quiz = None
        if old_quiz_id:
            try:
                old_quiz = Quiz.objects.get(pk=old_quiz_id)
            except:
                pass
        
        if old_quiz:
            if not old_quiz.completed:
                return redirect('quizes:my_quiz_proccess', old_quiz.pk, 1)

        # create quiz
        ip = request.META.get('HTTP_X_FORWARDED_FOR', request.META.get('REMOTE_ADDR', '')).split(',')[0].strip()
        quiz = Quiz.objects.create(
            difficulty=quiz_difficulty,
            questions_id = questions_id,
            ip = ip,
        )
        quiz.questions.add(*questions)

        request.session['quiz_id'] = str(quiz.pk)
        # print(request.META.get('HTTP_X_FORWARDED_FOR', request.META.get('REMOTE_ADDR', '')).split(',')[0].strip())
        # make QuizResponse for every single question
        temp_step = 1
        for item in questions_id:
            question = Question.objects.get(pk=item)
            quizRespone = QuizResponse.objects.create(
                quiz = quiz,
                question = question,
                answers = question.get_answers(),
                correct_answer = question.correct,
                step=temp_step
            )
            temp_step += 1

        return redirect ('quizes:my_quiz_proccess', quiz.pk, 1)
    

    context = dict(
        meta_description=_("A simple and experimental quiz about books"),
        page_title= _('My quiz'),
        quiz= quiz,
    ) 
    return render(
        request,
        'quizes/my_quiz.html',
        context
    )


def NewMyQuizProccessView(request, quiz_pk, step=1, error=None):
    quiz = get_object_or_404(Quiz, pk=quiz_pk)
    # check if the quiz completed or not
    if quiz.completed:
        return redirect('quizes:my_quiz_result', quiz_pk)
    #  the responses order by the step
    responses = quiz.responses.all().order_by('step')
    #  we always select the first step from the remaining steps
    remain_step = list(responses.filter(done=False).values_list('step', flat=True))
    if len(remain_step) > 0:
        current_step = remain_step[0]
    else:       
        return redirect('quizes:my_quiz_result', quiz_pk)
    
    required_msg = None

    if error == 'error':
        required_msg =  _('Please choose one')


    # print('responses is created', responses.count())
    response = responses.get(step=current_step)
    question = response.question
    answers = response.answers
    if request.method == 'POST':
        # user_answer = None
        # answer_list = response.answers 
        user_answer_string = request.POST.get('answer')
        # multiple = 0
        # print(request.POST.get('answer'))
        # for item in '1234':
        #     # print(f"{item}: ", request.POST.get(f"answer-{item}"))
        #     if request.POST.get(f"answer-{item}") == 'on':
        #         user_answer = f"answer-{item}"
        #         user_answer_string = response.answers[int(item) - 1]
        #         multiple += 1
        
        # if multiple > 1:
        #     return redirect ('quizes:my_quiz_proccess_error', 'error', quiz_pk, current_step)
        # if not user_answer_string:
        #     return redirect ('quizes:my_quiz_proccess_error', 'error', quiz_pk, current_step)
        #  we want to write user response to the record
        response.user_response = user_answer_string
        response.done = True
        response.save()
        # print('user respnse saved', response.user_response)
        # print(f'user response for step {step} stores to quizResponse')
        if step <= 4:
            return redirect('quizes:my_quiz_proccess', quiz_pk, current_step + 1)
        else:
            return redirect ('quizes:my_quiz_result', quiz.pk)

    context = dict(
        page_title= _('My quiz'),
        quiz= quiz,
        question= question,
        answers= answers,
        step= step, 
        required_ms= required_msg,
        meta_description=_("The page for answering book quiz questions"),
    )
    return render(
        request,
        'quizes/my_quiz_proccess.html',
        context
    )


def QuizResultView(request, pk):
    quiz = get_object_or_404(Quiz, pk=pk)
    responses = quiz.responses.all().order_by('step')

    responses_dict = {}

    sum = 0
    for response in responses:
        src = None
        # if response.question.link:
        #     try:
        #         res = requests.get(response.question.link)
        #     except:
        #         res = None
        #     if res:
        #         soup = BeautifulSoup(res.text, 'html.parser')
        #         src = f"https://ketabedamavand.com{soup.body.main.img['src']}"
        if not response.question.image:
            src = GrabBookData(response)
        responses_dict[response.id] = {
            'question': response.question,
            'result': response.result,
            # 'book_link': response.question.link,
            'src': src, 
            # 'image': response.question.image.url,
            'correct': response.correct_answer, 
            'user_response': response.user_response, 
        }
  
        if response.result:
            sum += 1
    
    quiz.final_result = sum 
    quiz.completed = True
    quiz.save(update_fields=['final_result', 'completed'])
    request.session['quiz_id'] = None

    compliment_qs = list(Compliment.objects.filter(difficulty=sum).values_list('content', flat=True))
    compliment = random.sample(compliment_qs, 1)
    if len(compliment) > 0:
        compliment = compliment[0]
    context = dict(
        meta_description=_("The result of Book quiz"),
        quiz= quiz,
        page_title= _('Quiz results'),
        responses= responses,

templates/quizes/my_quiz.html
{% extends '_base.html' %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}

{% endblock head %}
{% block title %}{{ page_title }}{% endblock title %}

{% block content %}
<div class="container bg-brown " >
    <h2 class="pt-4">{% trans "Book quiz" %}</h2>
    <div class="row py-5" id="">
        <div class="col">
            <p class="lead">{% trans "Welcome to book quiz" %}</p>
            <p>{% trans "How much do you know about books?" %}</p>
            <p>
                <a href="{% url 'quizes:my_quiz' %}?start=True" class="btn btn-warning">{% trans "Test yourself" %}</a>
            </p>
        
        </div>
    </div>
        
</div>
{% endblock content %}

templates/quizes/my_quiz_proccess.html
{% extends '_base.html' %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}

{% endblock head %}
{% block title %}{{ page_title }}{% endblock title %}

{% block content %}
<div class="container bg-brown " >
    <h2 class="pt-4">{% trans "Book quiz" %}</h2>
    <div class="row py-5" id="">
        <div class="col">
            {% if required_msg %}
            <p class="lead text-danger bg-light">{{ required_msg }}</p>
              
            {% endif %}
            <div class="d-flex">
                <p class="lead">{% trans "Question" %}: {{ step }}</p>
                <div class="ms-3 fs-6 diff-meter rounded">
                    <span class="rounded">ساده</span>
                    <span class="diff-marker" 
                    {% if question.difficulty == 1 %}
                    style="right: 5px;"                      
                    {% elif question.difficulty == 2 %}
                    style="right: 30px;"                      
                    {% elif question.difficulty == 3 %}
                    style="right: 60px;"                      
                    {% elif question.difficulty == 4 %}
                    style="right: 90px;"                      
                    {% elif question.difficulty == 5 %}
                    style="right: 112px;"                      
                    {% endif %}
                    
                    
                    ></span>
                    <span class="hard-text rounded text-light">سخت</span>
                </div>
            </div>
                {% for item in '12345' %}
                  
                {% endfor %} 
            <p class="lead">{{ question.description }}</p>
            <form action="" method="POST" onsubmit="subButton.disabled = true; return true;">
                {% csrf_token %}                
                {% for ans in answers %}
                <div class="form-check" action="">
                    <input class="form-check-input" type="radio" name="answer" value="{{ ans }}" id="answer-{{ forloop.counter }}" 
                    {% if forloop.counter == 1 %}required{% endif %}
                    >
                    <label class="form-check-label" for="answer-{{ forloop.counter }}">
                        {{ ans }}
                    </label>
                    
                </div>
                {% endfor %}
                {% if step < 6 %}
                <input type="submit" name="next" value="{% trans 'Next' %}" id="subButton" disabled="disabled" class="btn btn-warning my-3">
                {% else %}
                <input type="submit" name="result" value="{% trans 'Result' %}" id="subButton" disabled="disabled" class="btn btn-warning my-3">
                {% endif %}
                  
            </form>
            
        </div>
    </div>
        
</div>
{% endblock content %}

{% block script %}
<script>
    window.addEventListener("load", function() {
        document.getElementById("subButton").disabled=false; // or removeAttribute("disabled")
    }
)
</script>
  
{% endblock script %}

templates/quizes/question_create.html
{% extends '_base.html' %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}

{% endblock head %}
{% block title %}{{ page_title }}{% endblock title %}

{% block content %}
<div class="container bg-brown " >
    <h2 class="pt-4">{% trans "Create question" %}</h2>
    <div class="row py-5" id="question-create">
        <div class="col">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                <input type="submit" class="btn btn-light my-3" value="{% trans 'Save' %}">
            </form>        
        </div>
    </div>
        
</div>
{% endblock content %}

templates/quizes/question_list.html
{% extends '_base.html' %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}

{% endblock head %}
{% block title %}{{ page_title }}{% endblock title %}

{% block content %}
<div class="container bg-brown " >
    <h2 class="pt-4">{% trans "Question list" %}</h2>
    <form action="">
        <div class="input-group mb-3">            
            <input class="form-control" type="text" name="search" id="search"
            aria-label="Search button" aria-describedby="button-addon1" autofocus="on"
            >
            <button class="btn btn-outline-light" type="submit" id="button-addon1">
                {% trans 'Search' %}
            </button>      
        </div>
        {% if results %}
          {% for item in results %}
          {% if compliment %}
          <a href="{% url 'quizes:compliment_update' item.id %}" class="bg-light p-1 m-2">{{ item }}</a>
            {% else %}
          <a href="{% url 'quizes:question_update' item.id %}" class="bg-light p-1 m-2">{{ item }}</a>
          {% endif %}
          {% endfor %}
        {% endif %}      
    </form>
    {% if query %}
    {% if compliment %}
    <p>{{ query }} <a href="{% url 'quizes:compliment_list' %}" class="text-light fs-5 ms-3">&times;</a></p>
    {% else %}
    <p>{{ query }} <a href="{% url 'quizes:questions_list' %}" class="text-light fs-5 ms-3">&times;</a></p>
    {% endif %}
      
    {% endif %}
    <div class="row py-5" id="question-list">
        <div class="col">
            <a href="{% url 'quizes:question_create' %}" class="btn btn-warning my-2">{% trans "New question" %}</a>
            <a href="{% url 'quizes:questions_list' %}" class="btn btn-warning my-2">{% trans "Question list" %}</a>
            <a href="{% url 'quizes:compliment_create' %}" class="btn btn-warning my-2">{% trans "New compliment" %}</a>
            <a href="{% url 'quizes:compliment_list' %}" class="btn btn-warning my-2">{% trans "Compliment list" %}</a>
            <a href="{% url 'quizes:update_question_report' %}" class="btn btn-warning my-2">{% trans "Update question report" %}</a>
            <a href="{% url 'quizes:my_quiz' %}" class="btn btn-warning my-2">{% trans "New Quiz" %}</a>
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>{% trans "Question" %}</th>
                        <th>{% trans "Difficulty" %}</th>
                        <th>{% trans "Published" %}</th>
                        <th>{% trans "Link" %}</th>
                        <th>{% trans "Uses" %}</th>
                        <th>{% trans "Correct" %}</th>
                        <th>{% trans "Wrong" %}</th>
                        <th>{% trans "Correct percent" %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for que in object_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                            {% if compliment %}
                            <a href="{% url 'quizes:compliment_update' que.id %}">{{ que }}</a></td>
                            {% else %}
                            <a href="{% url 'quizes:question_update' que.id %}">{{ que }}</a></td>
                            {% endif %}
                        <td>{{ que.difficulty }}</td>                        
                        
                        {% if que.published %}
                        <td class="text-success fs-5">&check;</td>                        
                        {% else %}
                        <td class="text-danger fs-5">&times;</td>                        
                        {% endif %}
                        
                        {% if que.link %}
                        <td class="text-success fs-5">&check;</td>                        
                        {% else %}
                        <td class="text-danger fs-5">&times;</td>                        
                        {% endif %}
                        <td>{% if que.uses %}{{ que.uses }}{% endif %}</td>
                        <td>{% if que.correct_responses %}{{ que.correct_responses }}{% endif %}</td>
                        <td>{% if que.no_response %}{{ que.no_response }}{% endif %}</td>
                        <td>{{ que.get_correct_percent }}</td>
                    </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
        
        </div>
    </div>
        
</div>
{% endblock content %}

templates/quizes/show_results.html
{% extends '_base.html' %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
{% load social_share %}

{% block head %}
<style>
    
.compliment {  
  color:white;
  /* font-size:6em; */
  text-align:center;
  animation: neonGlow 2s infinite alternate ;
}

@keyframes neonGlow {
  0% {
    text-shadow: 0 0 10px rgba(255,255,255,.8),
                 0 0 20px rgba(255,255,255,.8),
                 0 0 22px  rgba(255,255,255,.8),
                 0 0 40px  rgba(66,220,219,.8),
                 0 0 60px  rgba(66,220,219,.8),
                 0 0 80px  rgba(66,220,219,.5),
                 0 0 100px rgba(66,220,219,.5),
                 0 0 140px rgba(66,220,219,.5),
                 0 0 200px rgba(66,220,219,.5);
  }
  100% {
    text-shadow: 0 0 2px rgba(255,255,255,.8),
                 0 0 8px rgba(255,255,255,.8),
                 0 0 10px rgba(255,255,255,.8),
                 0 0 20px rgba(66,220,219,.8),
                 0 0 30px rgba(66,220,219,.8),
                 0 0 40px rgba(66,220,219,.8),
                 0 0 50px rgba(66,220,219,.5),
                 0 0 80px rgba(66,220,219,.5);
  }
}

</style>
{% endblock head %}
{% block title %}{{ page_title }}{% endblock title %}

{% block content %}
<div class="container bg-brown" >
    <h2 class="pt-4">{% trans "Book quiz" %}</h2>
    {% if compliment %}
    <h3 class="border border-danger rounded m-3 p-2 text-center text-light compliment">{{ compliment }}</h3>
      
    {% endif %}
    <div class="row py-5" id="">
        <div class="col">
            <p class="lead">{% trans "Your resluts" %}</p>
            
            <table class="table">
                <thead>
                    <tr>
                        <th>{% trans "Question" %}</th>
                        <th>{% trans "Answer" %}</th>
                        <th>{% trans "Result" %}</th>
                        {% if sum < 5 %}
                          <th>{% trans "The books we should read" %}</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for id, respon in responses_dict.items %} 
                    {#  {% for respon in responses_list %} #}
                    <tr>
                        <td>{{ respon.question.description }}</td>
                        <td>{{ respon.correct }}</td>
                        <td>
                            {% if respon.result %}
                            <span class="text-success bold fs-4">1</span>
                            {% else %}
                            <span class="text-danger bold fs-4">0</span>
                            {% endif %}
                        </td>
                        <td >
                        {# if the image is availabel we show it#}

                        {% if respon.question.link %}
                            <a href="{{ respon.question.link }}" target="_blank" class="btn-special">                                
                                {% if respon.question.image.url != '' %}                                
                                <img src="{{ respon.question.image.url }}" class="rounded" alt="" width="100px" height="auto">

                                {% elif respon.src %}
                                <img src="{{ respon.src }}" class="rounded" alt="" width="100px" height="auto">
                                {% else %}
                                {% trans "See this book" %}
                                {% endif %}
                            </a>
                        {% endif %}

                        {% if not respon.result %}
                            <div class="my-1">

                                {% trans "Your answer was" %}: 
                                <span class="fw-bold text-danger">{{respon.user_response}}</span>
                                <br>
                            <br>
                            {% if respon.question.link %}
                               
                                <a href="{{ respon.question.link }}" target="_blank" class="btn-special">
                                    <span>{% trans "You may need this book" %} &#8599</span>
                                </a>
                            {% endif %}
                            </div>
                        {% else %}

                        {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="2">{% trans "Your result" %}</td>
                        <td class="lead text-warning">{{ sum }}</td>
                        <td></td>
                    </tr>
                </tfoot>
            </table> 
            {% comment %}
            
            <!-- does not work -->
            {% post_to_linkedin object_or_url %}
            <!-- compose without body text -->
            {% send_email "Book quiz" object_or_url %} 
            {% endcomment %}
            <div class="d-flex my-1">
                <p class="me-2">{% trans "Invite your friends to the game" %}:</p>
                <div class="me-2">
                    {% post_to_twitter "My book quiz result is {{ sum }}! What is yours?" "https://rahimagha.ir/fa/quizes/my-quiz/"  %}
                </div>
                <div class="me-2">
                    {% post_to_whatsapp "https://rahimagha.ir/fa/quizes/my-quiz/" %}
                </div>
                <div class="me-3">
                    {% post_to_telegram "My book quiz result is {{ sum }}! What is yours?" "https://rahimagha.ir/fa/quizes/my-quiz/" object_or_url %}
                </div>
                <div class="me-2">
                    {% copy_to_clipboard request.get_absolute_path object_or_url  %}
                </div>                
            </div>
            <div class="d-flex mt-3">
                <a href="{% url 'quizes:my_quiz' %}?start=True" class="btn btn-warning mx-1">{% trans "Do another quiz" %}</a>
                <a href="{% url 'quizes:my_quiz' %}?start=True&diff=2" class="btn btn-warning mx-1">{% trans "Do a little harder quiz" %}</a>
                <a href="{% url 'quizes:my_quiz' %}?start=True&diff=3" class="btn btn-danger mx-1">{% trans "Do a hard quiz" %}</a>
            </div>
            
        </div>
    </div>
        
</div>{% add_copy_script %}
{% endblock content %}